name: remote_rift_connector
description: "A local service that connects to and communicates with the League Client API."
version: 0.11.2
publish_to: "none"

environment:
  sdk: ^3.10.0

dev_dependencies:
  lints: ^6.0.0

  remote_rift_tools:
    git:
      url: https://github.com/tomwyr/remote-rift-foundation.git
      ref: 0.8.1
      path: packages/tools
