name: remote_rift_connector
description: "A local service that connects to and communicates with the League Client API."
version: 0.6.0
publish_to: "none"

environment:
  sdk: ^3.10.0

dev_dependencies:
  lints: ^6.0.0

workspace:
  - packages/api
  - packages/core
