name: remote_rift_api
publish_to: none
version: 0.11.2

environment:
  sdk: ^3.10.0

dependencies:
  args: ^2.7.0
  hooks: ^1.0.0
  json_annotation: ^4.10.0
  path: ^1.9.1
  pubspec_parse: ^1.5.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3

  remote_rift_core:
    git:
      url: https://github.com/tomwyr/remote-rift-connector.git
      ref: 0.11.2
      path: packages/core

dev_dependencies:
  test: ^1.25.6
  json_serializable: ^6.12.0
  build_runner: ^2.10.5
