name: remote_rift_api
description: A sample command-line application with basic argument parsing.
publish_to: none

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3
  bonsoir: ^6.0.1

  remote_rift_core:
    git:
      url: https://github.com/tomwyr/remote-rift-connector.git
      ref: 0.6.0
      path: packages/core

dev_dependencies:
  test: ^1.25.6
