name: remote_rift_connector_api
description: A sample command-line application with basic argument parsing.
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0

  remote_rift_connector_core:
    path: ../core

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
