name: remote_rift_core
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  json_annotation: ^4.9.0
  http: ^1.6.0

  remote_rift_utils:
    git:
      url: https://github.com/tomwyr/remote-rift-foundation.git
      ref: 0.5.0
      path: packages/utils

  equatable: ^2.0.8

dev_dependencies:
  build_runner: ^2.10.4
  json_serializable: ^6.11.3
  test: ^1.25.6
