name: remote_rift_core
publish_to: none
version: 0.10.0

environment:
  sdk: ^3.10.0

dependencies:
  json_annotation: ^4.9.0
  http: ^1.6.0
  equatable: ^2.0.8

  remote_rift_utils:
    git:
      url: https://github.com/tomwyr/remote-rift-foundation.git
      ref: 0.6.0
      path: packages/utils

dev_dependencies:
  build_runner: ^2.10.4
  json_serializable: ^6.11.3
  test: ^1.25.6
